language: node_js

node_js:
    - "6"
    - "7"

services:
    - mongodb
    - redis-server

addons:
    apt:
        sources:
            - mongodb-upstart
            - mongodb-3.2-precise
        packages:
            - mongodb-org-server
            - mongodb-org-shell

env:
    global:
        - MONGODB_URI=mongodb://localhost/goodjob
        - REDIS_URL=redis://localhost
        - NODE_ENV=test

install:
    - yarn install
    - ./bin/migrate

script:
    - npm test -- --timeout 30s
    - npm run coveralls || /bin/true
    - npm run lint
