language: node_js

node_js:
    - "6"

services:
    - mongodb

addons:
    apt:
        sources:
            - mongodb-upstart
            - mongodb-3.2-precise
        packages:
            - mongodb-org-server
            - mongodb-org-shell

env:
    global:
        - MONGODB_URI=mongodb://localhost/goodjob
        - NODE_ENV=test

install:
    - npm install

script:
    - npm test -- --timeout 30s
