version: '2'
services:
  node:
    image: node:10
    volumes:
      - ./:/app
    ports:
      - "12000:3000"
    links:
      - mongo:mongo
      - redis:redis
    working_dir: /app
    command: npm run dev
    environment:
      - MONGODB_URI=mongodb://mongo
      - MONGODB_DBNAME=goodjob
      - REDIS_URL=redis://redis
      - NODE_ENV=development
      - JWT_SECRET=DontUseMe
  mongo:
    image: mongo
  redis:
    image: redis
