defaults: &defaults
    working_directory: ~/app
    steps:
        - checkout
        - restore_cache:
            key: wtsb-{{ .Branch }}-{{ checksum "package.json" }}
        - run:
            name: Install Dependencies
            command: yarn install
        - run:
            name: Migrate
            command: npm run migrate
        - run:
            name: Unit test and API test
            command: npm test -- --timeout 30s
        - run:
            name: Coveralls
            command: npm run coveralls || /bin/true
        - run:
            name: Lint
            command: npm run lint
        - save_cache:
            key: wtsb-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
                - "~/.cache/yarn"

version: 2
jobs:
    build-node-7:
        <<: *defaults
        docker:
            - image: node:7
              environment:
                  MONGODB_URI: mongodb://localhost/goodjob
                  REDIS_URL: redis://localhost
                  NODE_ENV: test
            - image: mongo:3
            - image: redis
    build-node-8:
        <<: *defaults
        docker:
            - image: node:8
              environment:
                  MONGODB_URI: mongodb://localhost/goodjob
                  REDIS_URL: redis://localhost
                  NODE_ENV: test
            - image: mongo:3
            - image: redis
    build-apidoc:
        docker:
            - image: node
        working_directory: ~/app
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: yarn global add apidoc
            - run:
                name: Build
                command: apidoc -i routes/ -o apidoc/
            - add_ssh_keys
            - deploy:
                name: Deploy to github page
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        ./.circleci/deploy-apidoc.sh
                    fi
workflows:
    version: 2
    build_and_test:
        jobs:
            - build-node-7
            - build-node-8
            - build-apidoc:
                filters:
                    branches:
                        only: master
                requires:
                    - build-node-7
                    - build-node-8
