defaults: &defaults
    working_directory: ~/app
    steps:
        - checkout
        - restore_cache:
            key: wtsb-{{ .Branch }}-{{ checksum "package.json" }}
        - run:
            name: Install Dependencies
            command: yarn install
        - run:
            name: Migrate
            command: npm run migrate
        - run:
            name: Unit test and API test
            command: npm run test -- --timeout 30s
        - run:
            name: Unit test and API test
            command: npm run test:coverage -- --timeout 30s
        - run:
            name: Coveralls
            command: npm run coveralls || /bin/true
        - run:
            name: Lint
            command: npm run lint
        - save_cache:
            key: wtsb-{{ .Branch }}-{{ checksum "package.json" }}
            paths:
                - "~/.cache/yarn"

version: 2
jobs:
    build-node-7:
        <<: *defaults
        docker:
            - image: node:7
              environment:
                  MONGODB_URI: mongodb://localhost/goodjob
                  REDIS_URL: redis://localhost
                  NODE_ENV: test
            - image: mongo:3
            - image: redis
    build-node-8:
        <<: *defaults
        docker:
            - image: node:8
              environment:
                  MONGODB_URI: mongodb://localhost/goodjob
                  REDIS_URL: redis://localhost
                  NODE_ENV: test
            - image: mongo:3
            - image: redis
    build-apidoc:
        docker:
            - image: node
        working_directory: ~/app
        steps:
            - checkout
            - run:
                name: Install Dependencies
                command: yarn global add apidoc
            - run:
                name: Build
                command: apidoc -i routes/ -o apidoc/
            - add_ssh_keys
            - deploy:
                name: Deploy to github page
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        ./.circleci/deploy-apidoc.sh
                    fi
    build-docker:
        working_directory: ~/app
        docker:
            - image: buildpack-deps
        steps:
            - checkout
            - run:
                name: Install Docker client & Docker Compose
                command: ./.circleci/prepare-docker-compose.sh
            - setup_remote_docker
            - run:
                name: Build Docker Image
                command: docker-compose -f .circleci/docker-compose.yml build
            - deploy:
                name: Deploy docker image
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        ./.circleci/deploy-docker.sh
                    fi
    deploy-dev:
        working_directory: ~/app
        docker:
            - image: buildpack-deps
        steps:
            - run:
                name: Trigger Deploy
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        curl --user ${CIRCLE_API_TOKEN_FOR_DEPLOY}: \
                            --data build_parameters[CIRCLE_JOB]=build \
                            https://circleci.com/api/v1.1/project/github/mark86092/goodjob-deploy-ci/tree/api-dev
                    fi
    deploy-stage:
        working_directory: ~/app
        docker:
            - image: buildpack-deps
        steps:
            - run:
                name: Trigger Deploy
                command: |
                    if [ "${CIRCLE_PROJECT_USERNAME}" == "goodjoblife" ]; then
                        curl --user ${CIRCLE_API_TOKEN_FOR_DEPLOY}: \
                            --data build_parameters[CIRCLE_JOB]=build \
                            https://circleci.com/api/v1.1/project/github/mark86092/goodjob-deploy-ci/tree/api-stage-v4
                    fi
workflows:
    version: 2
    build_and_test:
        jobs:
            - build-node-7
            - build-node-8
            - build-apidoc:
                filters:
                    branches:
                        only:
                            - master
                            - dev
                requires:
                    - build-node-7
                    - build-node-8
            - build-docker:
                filters:
                    branches:
                        only:
                            - master
                            - dev
                requires:
                    - build-node-7
                    - build-node-8
            - deploy-dev:
                requires:
                    - build-docker
                filters:
                    branches:
                        only: dev
            - deploy-stage:
                requires:
                    - build-docker
                filters:
                    branches:
                        only: master
