version: 2
jobs:
    build:
        working_directory: ~/app
        docker:
            - image: node
              environment:
                  MONGODB_URI: mongodb://localhost/goodjob
                  REDIS_URL: redis://localhost
                  NODE_ENV: test
            - image: mongo:3
            - image: redis
        steps:
            - checkout
            - restore_cache:
                key: wtsb-{{ .Branch }}-{{ checksum "package.json" }}
            - run:
                name: Install Dependencies
                command: yarn install
            - run:
                name: Migrate
                command: npm run migrate
            - run:
                name: Unit test and API test
                command: npm test -- --timeout 30s
            - run:
                name: Lint
                command: npm run lint
            - save_cache:
                key: wtsb-{{ .Branch }}-{{ checksum "package.json" }}
                paths:
                    - "~/.cache/yarn"
