name: Github Actions CI

on:
  push:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 15]
    services:
      mongo:
        image: mongo:3.6
        ports:
          - 27017:27017
      redis:
        image: redis
        ports:
          - 6379:6379
    env:
      MONGODB_URI: mongodb://localhost
      MONGODB_DBNAME: goodjob
      REDIS_URL: redis://localhost
      NODE_ENV: test
      JWT_SECRET: DontUseMe
      VERIFY_EMAIL_JWT_SECRET: DontUseMe
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: Migrate
        run: npm run migrate
      - name: Unit test and API test
        run: npm run test -- --timeout 30s
      - name: Lint
        run: npm run lint
  docker:
    name: Deploy docker image
    if: github.repository == 'goodjoblife/WorkTimeSurvey-backend' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - test
    env:
      REGISTRY: docker.pkg.github.com
      REPO: goodjoblife/worktimesurvey-backend/api-server
      IMAGE: goodjoblife/api-server:latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: docker login ${REGISTRY} -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build the docker image
        run: docker-compose -f .github/docker-compose.yml build
      - name: Push production image
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag ${IMAGE} ${REGISTRY}/${REPO}:${GITHUB_SHA}
          docker push ${REGISTRY}/${REPO}:${GITHUB_SHA}
      - name: Push dev image
        if: github.ref == 'refs/heads/dev'
        run: |
          docker tag ${IMAGE} ${REGISTRY}/${REPO}-dev:dev
          docker push ${REGISTRY}/${REPO}-dev:dev
  deploy:
    if: github.repository == 'goodjoblife/WorkTimeSurvey-backend' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - name: Deploy dev
        if: github.ref == 'refs/heads/dev'
        run: |
          curl --user "${{ secrets.DEPLOY_CI_TOKEN }}" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type": "worktimesurveybackend-dev-published"}' \
            https://api.github.com/repos/mark86092/goodjob-deploy-ci/dispatches
